/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalprogra2;

import javax.swing.JOptionPane;

/**
 *
 * @author luiss
 */
public class Add extends javax.swing.JPanel {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        
        TextPrompt placeholder = new TextPrompt("...", txtnombre);
        placeholder.changeAlpha(0.30f);
        TextPrompt placeholder2 = new TextPrompt("...", txtartista);
        placeholder2.changeAlpha(0.30f);
        TextPrompt placeholder3 = new TextPrompt("...", txtalbum);
        placeholder3.changeAlpha(0.30f);
        TextPrompt placeholder4 = new TextPrompt("...", txtanio);
        placeholder4.changeAlpha(0.30f);
        TextPrompt placeholder5 = new TextPrompt("...", txtgenero);
        placeholder5.changeAlpha(0.30f);
        TextPrompt placeholder6 = new TextPrompt("...", txtrutacan);
        placeholder6.changeAlpha(0.30f);
        TextPrompt placeholder7 = new TextPrompt("...", txtrutaimg);
        placeholder7.changeAlpha(0.30f);
        TextPrompt placeholder8 = new TextPrompt("...", txtrutaletra);
        placeholder8.changeAlpha(0.30f);
        txtID.setText(""+(Cancion.getNoCanciones()+1));
        
        btnOtra.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtartista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtalbum = new javax.swing.JTextField();
        txtanio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgenero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnCancion = new javax.swing.JRadioButton();
        btnPodcast = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtrutacan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtrutaimg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtrutaletra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnOtra = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AÑADIR UNA CANCION");

        jSeparator1.setBackground(new java.awt.Color(80, 206, 0));
        jSeparator1.setForeground(new java.awt.Color(80, 206, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre/Titulo");

        txtnombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnombre.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtnombre.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Artista");

        txtartista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtartista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtartista.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtartista.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Album");

        txtalbum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtalbum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtalbum.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtalbum.setSelectionColor(new java.awt.Color(204, 204, 204));

        txtanio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtanio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtanio.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtanio.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año de Publicación");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Género Musical");

        txtgenero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtgenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtgenero.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtgenero.setSelectionColor(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo");

        btnCancion.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupTipo.add(btnCancion);
        btnCancion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancion.setForeground(new java.awt.Color(255, 255, 255));
        btnCancion.setText("Canción");

        btnPodcast.setBackground(new java.awt.Color(51, 51, 51));
        btnGroupTipo.add(btnPodcast);
        btnPodcast.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPodcast.setForeground(new java.awt.Color(255, 255, 255));
        btnPodcast.setText("Podcast");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ruta de la Canción");

        txtrutacan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtrutacan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrutacan.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtrutacan.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtrutacan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutacanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ruta de la Portada");

        txtrutaimg.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtrutaimg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrutaimg.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtrutaimg.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtrutaimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaimgActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ruta de la Letra");

        txtrutaletra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtrutaletra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtrutaletra.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtrutaletra.setSelectionColor(new java.awt.Color(204, 204, 204));
        txtrutaletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaletraActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID de la Nueva Canción");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(51, 51, 51));
        txtID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtID.setForeground(new java.awt.Color(80, 206, 0));
        txtID.setText("---");
        txtID.setBorder(null);
        txtID.setDisabledTextColor(new java.awt.Color(80, 206, 0));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(80, 206, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setText("Añadir Nueva Cancion");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnOtra.setBackground(new java.awt.Color(255, 255, 250));
        btnOtra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnOtra.setText("Añadir otra Cancion");
        btnOtra.setBorder(null);
        btnOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCancion)
                                .addGap(18, 18, 18)
                                .addComponent(btnPodcast))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnOtra, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtgenero)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtartista)
                                        .addComponent(txtalbum)
                                        .addComponent(txtanio)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(txtrutacan)
                                        .addComponent(txtrutaimg)
                                        .addComponent(txtrutaletra, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)))))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrutacan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtartista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrutaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtrutaletra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtanio, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOtra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancion)
                    .addComponent(btnPodcast))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtrutacanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutacanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutacanActionPerformed

    private void txtrutaimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaimgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutaimgActionPerformed

    private void txtrutaletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutaletraActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Lockear
        txtnombre.setEnabled(false);
        txtartista.setEnabled(false);
        txtalbum.setEnabled(false);
        txtanio.setEnabled(false);
        txtgenero.setEnabled(false);
        txtrutacan.setEnabled(false);
        txtrutaimg.setEnabled(false);
        txtrutaletra.setEnabled(false);
        
        btnOtra.setVisible(true);
        
        JOptionPane.showMessageDialog(null, "Canción Añadida con Exito", "Añadir Canción" , JOptionPane.INFORMATION_MESSAGE);
        
        String nombre=txtnombre.getText();
        String artista=txtartista.getText();
        String album=txtalbum.getText();
        int anio= Integer.parseInt(txtanio.getText());
        String genero=txtgenero.getText();
        String rutacan= txtrutacan.getText();
        String rutaimg= txtrutaimg.getText();
        String rutaletra= txtrutaletra.getText();
        
        Cancion nuevacancion= new Cancion(nombre,artista,album,anio,rutacan,rutaimg,rutaletra,genero,true);
        
        DatosGlobales.addCancion(nuevacancion);
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtraActionPerformed
        txtnombre.setEnabled(true);
        txtartista.setEnabled(true);
        txtalbum.setEnabled(true);
        txtanio.setEnabled(true);
        txtgenero.setEnabled(true);
        txtrutacan.setEnabled(true);
        txtrutaimg.setEnabled(true);
        txtrutaletra.setEnabled(true);
        
        txtnombre.setText("");
        txtartista.setText("");
        txtalbum.setText("");
        txtanio.setText("");
        txtgenero.setText("");
        txtrutacan.setText("");
        txtrutaimg.setText("");
        txtrutaletra.setText("");
        
        txtID.setText(""+(Cancion.getNoCanciones()+1));
        
        btnOtra.setVisible(false);
        
    }//GEN-LAST:event_btnOtraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JRadioButton btnCancion;
    private javax.swing.ButtonGroup btnGroupTipo;
    private javax.swing.JButton btnOtra;
    private javax.swing.JRadioButton btnPodcast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtalbum;
    private javax.swing.JTextField txtanio;
    private javax.swing.JTextField txtartista;
    private javax.swing.JTextField txtgenero;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrutacan;
    private javax.swing.JTextField txtrutaimg;
    private javax.swing.JTextField txtrutaletra;
    // End of variables declaration//GEN-END:variables
}
