/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalprogra2;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author luiss
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    Color NoSeleccionado = new Color(66,66,66,255);
    Color Seleccionado = new Color(102,102,102,255);
    ArrayList<Cancion> copiaDBCanciones= new ArrayList();
    ArrayList<Cancion> copiaDBRecientes= new ArrayList();

    String nombre;
    String rutaImg;
    String descrip;
    
    public Inicio() {
        initComponents();

        //Cambian
        Cancion copia=new Cancion();
        copiaDBRecientes = DatosGlobales.getdbRecientes();
        
        
        //Primera Cancion
        copia= copiaDBRecientes.get(0);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img1,rutaImg,txt1,nombre,desc1,descrip);
        
        //Segunda Cancion
        copia= copiaDBRecientes.get(1);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img2,rutaImg,txt2,nombre,desc2,descrip);
        
        //Tercera Cancion
        copia= copiaDBRecientes.get(2);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img3,rutaImg,txt3,nombre,desc3,descrip);
        
        //Cuarta Cancion
        copia= copiaDBRecientes.get(3);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img4,rutaImg,txt4,nombre,desc4,descrip);

        PLAY1.setVisible(false);
        PLAY2.setVisible(false);
        PLAY3.setVisible(false);
        PLAY4.setVisible(false);
        PLAY5.setVisible(false);
        PLAY6.setVisible(false);
        PLAY7.setVisible(false);
        PLAY8.setVisible(false);

        // ##############################################################################################
        //No Cambian
        //Cancion copia=new Cancion();
        copiaDBCanciones = DatosGlobales.getdbCanciones();
        
        //Cancion 1 estaticas      
        copia= copiaDBCanciones.get(0);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img5,rutaImg,txt5,nombre,desc5,descrip);
        
        
        //Cancion 2 estaticas
        copia= copiaDBCanciones.get(1);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img6,rutaImg,txt6,nombre,desc6,descrip);
        
        //Cancion 3 estatica
        copia= copiaDBCanciones.get(2);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img7,rutaImg,txt7,nombre,desc7,descrip);
        
        //Cancion 4 estatica
        copia= copiaDBCanciones.get(3);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img8,rutaImg,txt8,nombre,desc8,descrip);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        PLAY1 = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        PLAY2 = new javax.swing.JButton();
        Panel3 = new javax.swing.JPanel();
        img3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        PLAY3 = new javax.swing.JButton();
        Panel4 = new javax.swing.JPanel();
        img4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();
        desc4 = new javax.swing.JLabel();
        PLAY4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Panel5 = new javax.swing.JPanel();
        img5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JLabel();
        desc5 = new javax.swing.JLabel();
        PLAY5 = new javax.swing.JButton();
        Panel6 = new javax.swing.JPanel();
        img6 = new javax.swing.JLabel();
        txt6 = new javax.swing.JLabel();
        desc6 = new javax.swing.JLabel();
        PLAY6 = new javax.swing.JButton();
        Panel7 = new javax.swing.JPanel();
        img7 = new javax.swing.JLabel();
        txt7 = new javax.swing.JLabel();
        desc7 = new javax.swing.JLabel();
        PLAY7 = new javax.swing.JButton();
        Panel8 = new javax.swing.JPanel();
        img8 = new javax.swing.JLabel();
        txt8 = new javax.swing.JLabel();
        desc8 = new javax.swing.JLabel();
        PLAY8 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        Panel1.setBackground(new java.awt.Color(66, 66, 66));
        Panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel1MouseMoved(evt);
            }
        });

        img1.setBackground(new java.awt.Color(204, 204, 255));

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("jLabel2");

        desc1.setForeground(new java.awt.Color(204, 204, 204));
        desc1.setText("jLabel3");
        desc1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY1.setBackground(new java.awt.Color(80, 206, 0));
        PLAY1.setForeground(new java.awt.Color(255, 255, 255));
        PLAY1.setText("⏯");
        PLAY1.setBorder(null);
        PLAY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt1)
                .addGap(18, 18, 18)
                .addComponent(desc1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2.setBackground(new java.awt.Color(66, 66, 66));
        Panel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel2MouseMoved(evt);
            }
        });

        img2.setBackground(new java.awt.Color(204, 204, 255));

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setText("jLabel2");

        desc2.setForeground(new java.awt.Color(204, 204, 204));
        desc2.setText("jLabel4");
        desc2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY2.setBackground(new java.awt.Color(80, 206, 0));
        PLAY2.setForeground(new java.awt.Color(255, 255, 255));
        PLAY2.setText("⏯");
        PLAY2.setBorder(null);
        PLAY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(desc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt2)
                .addGap(18, 18, 18)
                .addComponent(desc2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel3.setBackground(new java.awt.Color(66, 66, 66));
        Panel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel3MouseMoved(evt);
            }
        });

        img3.setBackground(new java.awt.Color(204, 204, 255));

        txt3.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setText("jLabel2");

        desc3.setForeground(new java.awt.Color(204, 204, 204));
        desc3.setText("jLabel5");
        desc3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY3.setBackground(new java.awt.Color(80, 206, 0));
        PLAY3.setForeground(new java.awt.Color(255, 255, 255));
        PLAY3.setText("⏯");
        PLAY3.setBorder(null);
        PLAY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel3Layout = new javax.swing.GroupLayout(Panel3);
        Panel3.setLayout(Panel3Layout);
        Panel3Layout.setHorizontalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(desc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Panel3Layout.setVerticalGroup(
            Panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt3)
                .addGap(18, 18, 18)
                .addComponent(desc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel4.setBackground(new java.awt.Color(66, 66, 66));
        Panel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel4MouseMoved(evt);
            }
        });

        img4.setBackground(new java.awt.Color(204, 204, 255));

        txt4.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setText("jLabel2");

        desc4.setForeground(new java.awt.Color(204, 204, 204));
        desc4.setText("jLabel6");
        desc4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY4.setBackground(new java.awt.Color(80, 206, 0));
        PLAY4.setForeground(new java.awt.Color(255, 255, 255));
        PLAY4.setText("⏯");
        PLAY4.setBorder(null);
        PLAY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel4Layout = new javax.swing.GroupLayout(Panel4);
        Panel4.setLayout(Panel4Layout);
        Panel4Layout.setHorizontalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(img4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Panel4Layout.setVerticalGroup(
            Panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt4)
                .addGap(18, 18, 18)
                .addComponent(desc4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ÚLTIMOS LANZAMIENTOS");

        jSeparator1.setBackground(new java.awt.Color(80, 206, 0));
        jSeparator1.setForeground(new java.awt.Color(80, 206, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ESCUCHADAS RECIENTEMENTE");

        Panel5.setBackground(new java.awt.Color(66, 66, 66));
        Panel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel5MouseMoved(evt);
            }
        });

        img5.setBackground(new java.awt.Color(204, 204, 255));

        txt5.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt5.setForeground(new java.awt.Color(255, 255, 255));
        txt5.setText("jLabel2");

        desc5.setForeground(new java.awt.Color(204, 204, 204));
        desc5.setText("jLabel3");
        desc5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY5.setBackground(new java.awt.Color(80, 206, 0));
        PLAY5.setForeground(new java.awt.Color(255, 255, 255));
        PLAY5.setText("⏯");
        PLAY5.setBorder(null);
        PLAY5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel5Layout = new javax.swing.GroupLayout(Panel5);
        Panel5.setLayout(Panel5Layout);
        Panel5Layout.setHorizontalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt5, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(img5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        Panel5Layout.setVerticalGroup(
            Panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt5)
                .addGap(18, 18, 18)
                .addComponent(desc5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel6.setBackground(new java.awt.Color(66, 66, 66));
        Panel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel6MouseMoved(evt);
            }
        });

        img6.setBackground(new java.awt.Color(204, 204, 255));

        txt6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt6.setForeground(new java.awt.Color(255, 255, 255));
        txt6.setText("jLabel2");

        desc6.setForeground(new java.awt.Color(204, 204, 204));
        desc6.setText("jLabel4");
        desc6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY6.setBackground(new java.awt.Color(80, 206, 0));
        PLAY6.setForeground(new java.awt.Color(255, 255, 255));
        PLAY6.setText("⏯");
        PLAY6.setBorder(null);
        PLAY6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel6Layout = new javax.swing.GroupLayout(Panel6);
        Panel6.setLayout(Panel6Layout);
        Panel6Layout.setHorizontalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(img6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Panel6Layout.setVerticalGroup(
            Panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt6)
                .addGap(18, 18, 18)
                .addComponent(desc6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel7.setBackground(new java.awt.Color(66, 66, 66));
        Panel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel7MouseMoved(evt);
            }
        });

        img7.setBackground(new java.awt.Color(204, 204, 255));

        txt7.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt7.setForeground(new java.awt.Color(255, 255, 255));
        txt7.setText("jLabel2");

        desc7.setForeground(new java.awt.Color(204, 204, 204));
        desc7.setText("jLabel5");
        desc7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY7.setBackground(new java.awt.Color(80, 206, 0));
        PLAY7.setForeground(new java.awt.Color(255, 255, 255));
        PLAY7.setText("⏯");
        PLAY7.setBorder(null);
        PLAY7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel7Layout = new javax.swing.GroupLayout(Panel7);
        Panel7.setLayout(Panel7Layout);
        Panel7Layout.setHorizontalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(img7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Panel7Layout.setVerticalGroup(
            Panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt7)
                .addGap(18, 18, 18)
                .addComponent(desc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel8.setBackground(new java.awt.Color(66, 66, 66));
        Panel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Panel8MouseMoved(evt);
            }
        });

        img8.setBackground(new java.awt.Color(204, 204, 255));

        txt8.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txt8.setForeground(new java.awt.Color(255, 255, 255));
        txt8.setText("jLabel2");

        desc8.setForeground(new java.awt.Color(204, 204, 204));
        desc8.setText("jLabel6");
        desc8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        PLAY8.setBackground(new java.awt.Color(80, 206, 0));
        PLAY8.setForeground(new java.awt.Color(255, 255, 255));
        PLAY8.setText("⏯");
        PLAY8.setBorder(null);
        PLAY8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAY8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel8Layout = new javax.swing.GroupLayout(Panel8);
        Panel8.setLayout(Panel8Layout);
        Panel8Layout.setHorizontalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(img8, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(desc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PLAY8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Panel8Layout.setVerticalGroup(
            Panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(img8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PLAY8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(Panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(Panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseMoved
        PLAY1.setVisible(true);
        Panel1.setBackground(Seleccionado);
    }//GEN-LAST:event_Panel1MouseMoved

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved

        //todos los plays
        PLAY1.setVisible(false);
        PLAY2.setVisible(false);
        PLAY3.setVisible(false);
        PLAY4.setVisible(false);
        PLAY5.setVisible(false);
        PLAY6.setVisible(false);
        PLAY7.setVisible(false);
        PLAY8.setVisible(false);
        
        Panel1.setBackground(NoSeleccionado);
        Panel2.setBackground(NoSeleccionado);
        Panel3.setBackground(NoSeleccionado);
        Panel4.setBackground(NoSeleccionado);
        Panel5.setBackground(NoSeleccionado);
        Panel6.setBackground(NoSeleccionado);
        Panel7.setBackground(NoSeleccionado);
        Panel8.setBackground(NoSeleccionado);

        
        //Refrescar el array de Recientes
        
        //Cambian
        Cancion copia=new Cancion();
        copiaDBCanciones = DatosGlobales.getdbRecientes();
        
        
        //Primera Cancion
        copia= copiaDBCanciones.get(0);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img1,rutaImg,txt1,nombre,desc1,descrip);
        
        //Segunda Cancion
        copia= copiaDBCanciones.get(1);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img2,rutaImg,txt2,nombre,desc2,descrip);
        
        //Tercera Cancion
        copia= copiaDBCanciones.get(2);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img3,rutaImg,txt3,nombre,desc3,descrip);
        
        //Cuarta Cancion
        copia= copiaDBCanciones.get(3);
        nombre= copia.getNombre();
        rutaImg= copia.getImageRoot();
        descrip= CrearDescripcion(copia);
        
        SetCancion(img4,rutaImg,txt4,nombre,desc4,descrip);


    }//GEN-LAST:event_jPanel1MouseMoved

    private void Panel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseMoved
        PLAY2.setVisible(true);
        Panel2.setBackground(Seleccionado);
    }//GEN-LAST:event_Panel2MouseMoved

    private void Panel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel3MouseMoved
        PLAY3.setVisible(true);
        Panel3.setBackground(Seleccionado);
    }//GEN-LAST:event_Panel3MouseMoved

    private void Panel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel4MouseMoved
        PLAY4.setVisible(true);
        Panel4.setBackground(Seleccionado);

    }//GEN-LAST:event_Panel4MouseMoved

    private void Panel5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel5MouseMoved
        PLAY5.setVisible(true);
        Panel5.setBackground(Seleccionado);

    }//GEN-LAST:event_Panel5MouseMoved

    private void Panel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel6MouseMoved
        PLAY6.setVisible(true);
        Panel6.setBackground(Seleccionado);

    }//GEN-LAST:event_Panel6MouseMoved

    private void Panel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel7MouseMoved
        PLAY7.setVisible(true);
        Panel7.setBackground(Seleccionado);

    }//GEN-LAST:event_Panel7MouseMoved

    private void Panel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel8MouseMoved
        PLAY8.setVisible(true);
        Panel8.setBackground(Seleccionado);

    }//GEN-LAST:event_Panel8MouseMoved

    private void PLAY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY1ActionPerformed
        copiaDBRecientes=DatosGlobales.getdbRecientes();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBRecientes.get(0);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY1ActionPerformed

    private void PLAY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY2ActionPerformed
        copiaDBRecientes=DatosGlobales.getdbRecientes();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBRecientes.get(1);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY2ActionPerformed

    private void PLAY5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY5ActionPerformed
        copiaDBCanciones=DatosGlobales.getdbCanciones();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBCanciones.get(0);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY5ActionPerformed

    private void PLAY6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY6ActionPerformed
        copiaDBCanciones=DatosGlobales.getdbCanciones();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBCanciones.get(1);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY6ActionPerformed

    private void PLAY7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY7ActionPerformed
        copiaDBCanciones=DatosGlobales.getdbCanciones();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBCanciones.get(2);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY7ActionPerformed

    private void PLAY8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY8ActionPerformed
        
        copiaDBCanciones=DatosGlobales.getdbCanciones();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBCanciones.get(3);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY8ActionPerformed

    private void PLAY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY3ActionPerformed
        copiaDBRecientes=DatosGlobales.getdbRecientes();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBRecientes.get(2);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY3ActionPerformed

    private void PLAY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAY4ActionPerformed
        copiaDBRecientes=DatosGlobales.getdbRecientes();
        Cancion copiabtn1=new Cancion();
        copiabtn1= copiaDBRecientes.get(3);
        
        //Mostrar la mas reciente primero
        Cancion pos0=new Cancion();
        Cancion pos1=new Cancion();
        Cancion pos2=new Cancion();
        Cancion pos3= new Cancion();
        
        pos0= copiaDBRecientes.get(0);
        pos1= copiaDBRecientes.get(1);
        pos2= copiaDBRecientes.get(2);
        pos3= copiaDBRecientes.get(3);
        
        int idcopia=copiabtn1.getIDcancion();
        int id0=pos0.getIDcancion();
        int id1=pos1.getIDcancion();
        int id2=pos2.getIDcancion();        
        int id3=pos3.getIDcancion();
        
        //Comprobar que la cancion a reproducir sea diferente a las que ya estan en el arrayRecientes
        if ((idcopia!=id0)&&(idcopia!=id1)&&(idcopia!=id2)&&(idcopia!=id3) ) 
        {
            copiaDBRecientes.clear();

            copiaDBRecientes.add(copiabtn1);
            copiaDBRecientes.add(pos0);
            copiaDBRecientes.add(pos1);
            copiaDBRecientes.add(pos2);

            DatosGlobales.setdbRecientes(copiaDBRecientes);
        }
        
        //Fin 
        
        DatosGlobales.setCancionSeleccionada(copiabtn1);
        
        //JOptionPane.showMessageDialog(null, "Cancion escogida: "+ copiabtn1.getNombre());
        
        //Mostar reproductor
        Reproductor repro= new Reproductor();
        repro.setVisible(true);
        repro.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_PLAY4ActionPerformed
    
    public void SetCancion(JLabel imagen,String root,JLabel txt, String Cancion, JLabel desc, String descripcion)
    {
        imagen.setSize(216, 166);
        SetImageLabel(imagen, root);
        txt.setText(Cancion);
        desc.setText(descripcion);
    }
    
    public String CrearDescripcion(Cancion rola)
    {
        String artista= rola.getArtista();
        String album= rola.getAlbum();
        int anio= rola.getAnio();
        
        String descripcion= artista+" - "+ album+" ("+anio+")";
        return descripcion;
    }
    
    public void SetImageLabel(JLabel label, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_DEFAULT));
        label.setIcon(icon);
        this.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PLAY1;
    private javax.swing.JButton PLAY2;
    private javax.swing.JButton PLAY3;
    private javax.swing.JButton PLAY4;
    private javax.swing.JButton PLAY5;
    private javax.swing.JButton PLAY6;
    private javax.swing.JButton PLAY7;
    private javax.swing.JButton PLAY8;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JPanel Panel3;
    private javax.swing.JPanel Panel4;
    private javax.swing.JPanel Panel5;
    private javax.swing.JPanel Panel6;
    private javax.swing.JPanel Panel7;
    private javax.swing.JPanel Panel8;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    private javax.swing.JLabel desc4;
    private javax.swing.JLabel desc5;
    private javax.swing.JLabel desc6;
    private javax.swing.JLabel desc7;
    private javax.swing.JLabel desc8;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JLabel img8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    private javax.swing.JLabel txt5;
    private javax.swing.JLabel txt6;
    private javax.swing.JLabel txt7;
    private javax.swing.JLabel txt8;
    // End of variables declaration//GEN-END:variables
}
